version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: betarme-dev
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  # Open localhost:5433 in the browser
  # NOTE: use `db`(the service name) as the host when connecting to the database from pgadmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5433:80"
    depends_on:
      - db
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    ports:
      # localstack gateway, access localhost:4566/health to see services
      - "4566:4566"
